### ISSUE TITLE
Lucas Pham Documentation

### ISSUE THREAD

**Issue by spectreseldom** [CSAllenISD/2023-ISP-Ludicrous#7]
Add my github username to the README.md in my repository

Adjacent to my username provide a list of role(s) for which I am responsible

Below my username (indented) add a link to my CoderMerlin Digital Portfolio
Ur still in our repository. Specify ur own project. 
jkvdfhkuhkvbjDFV

**Comment by JacobFesseha** [comment]
u in the wrong place mm=y guy

**Comment by spectreseldom** [comment]
What's your real project?

**Comment by JacobFesseha** [comment]
get outta here
